local_epg_url: "http://LERRnas:8181/epg.xml"

keep_channels: []

keep_groups:
  # South Africa
  - "AF | SOUTH AFRICA"

  # UK
  - "UK | GENERAL"
  - "UK | NEWS"
  - "UK | ENTERTAINMENT"
  - "UK | DOCUMENTARIES"
  - "UK | AMAZON PRIME"
  - "UK | HBO MAX"
  - "UK | MOVIES"
  - "UK | MOVIES 24/7"
  - "UK | SERIES 24/7"
  - "UK | SPORTS"
  - "UK | SPORTS SKY SPORTS+"

  # VIP Sports
  - "VIP | SPORTS FORMULA 1"
  - "VIP | SPORTS RUGBY"
  - "VIP | SPORTS TENNIS"
  - "VIP | SPORTS FOOT"
  - "VIP | SPORTS MOTOGP"
  - "VIP | SPORTS CRICKET"
  - "VIP | 4K UHD"

  # Netherlands
  - "NL | NETHERLANDS"
  - "NL | SPORTS F1-TV"
  - "NL | MOVIES"
  - "NL | MOVIES KIDS"
  - "NL | MOVIES 4K"

  # English VOD
  - "EN | MOVIES"
  - "EN | MOVIES LATEST"
  - "EN | DOCUMENTARY"
  - "EN | 4K UHD HEVC"
  - "EN | MOVIES KIDS"
