local_epg_url: "http://LERRnas:8181/epg.xml"

keep_channels: []

keep_groups:
  # South Africa
  - "AF | SOUTH AFRICA"

  # UK
  - "UK | GENERAL"
  - "UK | NEWS"
  - "UK | ENTERTAINMENT"
  - "UK | MUSIC"
  - "UK | KIDS"
  - "UK | DOCUMENTARIES"
  - "UK | AMAZON PRIME"
  - "UK | HBO MAX"
  - "UK | MOVIES"
  - "UK | MOVIES 24/7"
  - "UK | SERIES 24/7"
  - "UK | REGIONAL/EXTRA'S"
  - "UK | INTERNATIONAL/RELIGIOUS"
  - "UK | SPORTS"
  - "UK | SPORTS EPL"
  - "UK | SPORTS EFL"
  - "UK | SPORTS SKY SPORTS+"
  - "UK | SPORTS DAZN"
  - "UK | SPORTS CLUBS"
  - "UK | SPORTS SPFL"
  - "UK | SPORTS HUB PREMIER"

  # VIP Sports
  - "VIP | SPORTS FORMULA 1"
  - "VIP | SPORTS RUGBY"
  - "VIP | SPORTS TENNIS"
  - "VIP | SPORTS FOOT"
  - "VIP | SPORTS INT. FOOTBALL"
  - "VIP | SPORTS PPV BOXING"
  - "VIP | SPORTS PPV UFC"
  - "VIP | SPORTS PPV EVENTS"
  - "VIP | SPORTS MOTOGP"
  - "VIP | SPORTS CRICKET"
  - "VIP | SPORTS MATCHROOM"
  - "VIP | SPORTS LIGUE 1"
  - "VIP | SPORTS ASTRO"
  - "VIP | SPORTS NOW SPORTS"
  - "VIP | SPORTS TRILLER TV"
  - "VIP | 4K UHD"

  # Netherlands
  - "NL | NETHERLANDS"
  - "NL | SPORTS"
  - "NL | SPORTS DAZN"
  - "NL | SPORTS F1-TV"
  - "NL | SPORTS VIAPLAY"
  - "NL | SPORTS GLORY / UFC"
  - "NL | NOS LIVE EVENTS"
  - "NL | MOVIES"
  - "NL | TV SHOWS"
  - "NL | MOVIES KIDS"
  - "NL | CINEMA 24/7"
  - "NL | MOVIES 4K"

  # English VOD
  - "EN | TV SHOWS"
  - "EN | MOVIES"
  - "EN | MOVIES LATEST"
  - "EN | DOCUMENTARY"
  - "EN | 4K UHD HEVC"
  - "EN | ANIME"
  - "EN | MOVIES KIDS"
  - "EN | STAND-UP COMEDY"
  - "EN | LIVE CONCERTS"
  - "EN | TV SHOWS ANIME"
  - "EN | TV SHOWS DOCUMENTARY"
  - "EN | TV SHOWS KIDS CARTOON"
